"""add video model

Revision ID: 52ebbc6c23e7
Revises: 2e91430a9737
Create Date: 2026-09-07 12:35:58.851758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ebbc6c23e7'
down_revision: Union[str, Sequence[str], None] = '2e91430a9737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('video_resolution', sa.String(length=50), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('time_of_day', sa.String(length=20), nullable=False),
    sa.Column('tracing', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('file_object_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_object_key')
    )
    op.create_index(op.f('ix_video_author_id'), 'video', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_author_id'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
