"""add_d_camera_table

Revision ID: 7de731abf283
Revises: 2cb0922e95bc
Create Date: 2026-09-02 17:40:49.196602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de731abf283'
down_revision: Union[str, Sequence[str], None] = '2cb0922e95bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_camera',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('camera_name', sa.String(length=255), nullable=False),
    sa.Column('camera_place', sa.String(length=500), nullable=True),
    sa.Column('camera_place_cd', sa.Integer(), nullable=True),
    sa.Column('camera_latitude', sa.Float(), nullable=False),
    sa.Column('camera_longitude', sa.Float(), nullable=False),
    sa.Column('camera_type', sa.String(length=100), nullable=True),
    sa.Column('camera_type_cd', sa.Integer(), nullable=True),
    sa.Column('camera_class', sa.String(length=100), nullable=True),
    sa.Column('camera_class_cd', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('azimuth', sa.Integer(), nullable=True),
    sa.Column('archive', sa.SmallInteger(), nullable=False),
    sa.Column('process_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_d_camera_camera_id'), 'd_camera', ['camera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_d_camera_camera_id'), table_name='d_camera')
    op.drop_table('d_camera')
    # ### end Alembic commands ###
