"""camera <-> videos relation

Revision ID: ac8c2ce7da59
Revises: c72076525ac7
Create Date: 2026-09-08 18:07:06.040510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8c2ce7da59'
down_revision: Union[str, Sequence[str], None] = 'c72076525ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('camera_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_video_camera_id'), 'video', ['camera_id'], unique=False)
    op.create_foreign_key(None, 'video', 'd_camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_index(op.f('ix_video_camera_id'), table_name='video')
    op.drop_column('video', 'camera_id')
    # ### end Alembic commands ###
