"""add one-to-one relation in video <-> analysis

Revision ID: 558f35c43daa
Revises: ff1caa14514c
Create Date: 2026-09-22 09:05:56.833251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558f35c43daa'
down_revision: Union[str, Sequence[str], None] = 'ff1caa14514c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_video_id'), table_name='analyses')
    op.create_index(op.f('ix_analyses_video_id'), 'analyses', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_video_id'), table_name='analyses')
    op.create_index(op.f('ix_analyses_video_id'), 'analyses', ['video_id'], unique=False)
    # ### end Alembic commands ###
