"""add preview_object_key in video model

Revision ID: 601a04bc3cad
Revises: 4cbec3ac3eca
Create Date: 2026-09-08 19:49:30.022522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601a04bc3cad'
down_revision: Union[str, Sequence[str], None] = '4cbec3ac3eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('preview_object_key', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'video', ['preview_object_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_column('video', 'preview_object_key')
    # ### end Alembic commands ###
