"""make video metadata nullable

Revision ID: 99b79a1c7fe9
Revises: 06d8b58ae213
Create Date: 2026-09-21 12:29:59.835675

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99b79a1c7fe9"
down_revision: Union[str, Sequence[str], None] = "06d8b58ae213"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video",
        "duration",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "video", "video_resolution", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "video", "fps", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "video",
        "preview_object_key",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video",
        "preview_object_key",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "video", "fps", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "video", "video_resolution", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "video",
        "duration",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###
